### ISSUE TITLE
IP2Location LITE Support

### ISSUE THREAD

**Issue by m-cameron** [RobThree/IP2Country#1]
Hi Rob,

Do you plan to support the free IP2Location LITE database?

**Comment by RobThree** [comment]
I'll look into it.

Note to self: https://lite.ip2location.com

**Comment by RobThree** [comment]
[Here you go](https://www.nuget.org/packages/IP-2-Country.IP2Location.Lite/)

Please let me know if it works for you. It only supports the .CSV files (I would like to support the .BIN files sometime later). You'll need an account; then you can download these files:

[DB1 - IPv4](https://lite.ip2location.com/download?db=db1&type=csv&version=4)
[DB3 - IPv4](https://lite.ip2location.com/download?db=db3&type=csv&version=4)
[DB5 - IPv4](https://lite.ip2location.com/download?db=db5&type=csv&version=4)
[DB9 - IPv4](https://lite.ip2location.com/download?db=db9&type=csv&version=4)
[DB11 - IPv4](https://lite.ip2location.com/download?db=db11&type=csv&version=4)

[DB1 - IPv6](https://lite.ip2location.com/download?db=db1&type=csv&version=6)
[DB3 - IPv6](https://lite.ip2location.com/download?db=db3&type=csv&version=6)
[DB5 - IPv6](https://lite.ip2location.com/download?db=db5&type=csv&version=6)
[DB9 - IPv6](https://lite.ip2location.com/download?db=db9&type=csv&version=6)
[DB11 - IPv6](https://lite.ip2location.com/download?db=db11&type=csv&version=6)

Which is in what files is shown [on their website](https://lite.ip2location.com/):
![image](https://user-images.githubusercontent.com/607888/54031170-46d52700-41ae-11e9-9e39-bb0a37815766.png)

I may, at some time, also look into supporting PX1, PX2, PX3, PX4 and ASN databases and all paid variants. PR's are always welcome.

<sub>It's a shame that they stuff their zip's with all kinds of other files (README's and whatnots), so you'll have to extract the zipfiles yourself before you can point the `IP2LocationFileSource` to the .CSV. We already support reading zipped and gzipped files directly, as long as they ONLY contain CSV data.</sub>

**Comment by RobThree** [comment]
@m-cameron Just... out of curiosity: I've been checking out [your GitHub activity](https://github.com/m-cameron?tab=overview) and it seems you almost exclusively open issues like this one. All sorts of random projects, all they have in common is they use some ip-to-location (related) stuff and you open issues with all these projects to support IP2Location (LITE). Not that it matters much but could you explain why that is? I don't believe you use, or are even interested in, all these projects. So what's the deal then?

* https://github.com/dimsav/laravel-ip-service/issues/2
* https://github.com/madisvain/geolocationapi/issues/2
* https://github.com/zmap/zmap/issues/540
* https://github.com/DiceTechnology/dice-where/issues/43
* https://github.com/Chnkr/python-libipintel/issues/2
* https://github.com/nigelhorne/Geo-Coder-Free/issues/44
* https://github.com/Graylog2/graylog2-server/issues/4919
* https://github.com/eldy/awstats/issues/102
* https://github.com/ILLKX/LookingGlass-En/issues/1
* https://github.com/adshares/aduser/issues/18
* https://github.com/kubernetes/ingress-nginx/issues/2571
* https://github.com/fireeye/GeoLogonalyzer/issues/1
* https://github.com/matomo-org/matomo/issues/12411
* https://github.com/fxfactorial/ocaml-maxminddb/issues/1
* https://github.com/nem-c/ip2loc-lite/issues/2
* https://github.com/JuliaWeb/GeoIP.jl/issues/10
* https://github.com/fgsch/libvmod-geoip2/issues/5
* https://github.com/abh/geodns/issues/84
* https://github.com/yoanisgil/easygeoip/issues/1
* https://github.com/magento-hackathon/Sandfox_GeoIP/issues/25

And in only one or two issues you ever bothered to answer any questions or post a followup. This feels kinda fishy / spammy to me. And the *few* issues you **didn't** refer to IP2Location had to do with the FraudLabs Pro API...
